---

- name: System Prerequisites | Update
  become: true
  become_user: root
  import_tasks: system-update.yml
  when: sys_prereq_update | bool

- name: System Prerequisites | Intall Python3 pre-requisites packages
  become: true
  become_user: root
  import_tasks: system-python3-prerequisite.yml
  when: sys_prereq_python3 | bool