---

###  Gestione asincrona dello yum update    
- name: System Prerequisites | Update | Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: _yum_update


- name: System Prerequisites | Update | Debug updates
  debug:
    msg: "{{ _yum_update }}"
  when: _yum_update.changed


- name: System Prerequisites | Update | Clean cache
  command: yum clean all
  args:
    warn: false
  when: _yum_update.changed


- name: System Prerequisites | Update | Reboot
  reboot:
    msg: "Reboot initiated by Ansible for a system update"
    pre_reboot_delay: "{{ sys_prereq_reboot_pre_delay }}"
    post_reboot_delay: "{{ sys_prereq_reboot_post_delay }}"
    reboot_timeout: "{{ sys_prereq_reboot_timeout }}"
  when: 
    - sys_prereq_reboot_enabled | bool
    - _yum_update.changed
    
